apiVersion: 1
datasources:
  - name: SQLite
    type: frser-sqlite-datasource
    uid: sqlite-monitoring
    access: proxy
    isDefault: true
    jsonData:
      path: /var/lib/grafana/monitoring/metrics.db
